---
nginx_locations:
  - config_file: location-app2.conf
    uri: "/app2"
    proxy_pass: "http://127.0.0.1:8000/app2"
    proxy_redirect: "off"
    proxy_next_upstream: "off"
    proxy_set_header:
      - "host $http_post"
      - "X-Forwarded-Proto $scheme"
    proxy_read_timeout: 600
    proxy_send_timeout: 60